import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import React, { ReactNode } from "react";
import { Box } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Information Page",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

export default function InfoLayout({ children }: Props) {
  return (
    <div>
      <Navbar />
      <Box pt="80px" px={4} pb={10}>
        {children}
      </Box>
    </div>
  );
}
